release:
	mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release ../ && make

debug:
	mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug ../ && make

remove: 
	rm -rf bin

.PHONY: remove 
